CREATE TABLE Users (
    ID UNIQUEIDENTIFIER PRIMARY KEY  ,
    Name NVARCHAR(30) NOT NULL,
    Password NVARCHAR(30) NOT NULL,
    Salt NVARCHAR(5) NOT NULL
);

CREATE TABLE Songs (
    ID UNIQUEIDENTIFIER PRIMARY KEY ,
    Name NVARCHAR(30) NOT NULL
    
);

CREATE TABLE Media (
    ID UNIQUEIDENTIFIER PRIMARY KEY ,
    URL NVARCHAR(255) NOT NULL,
    Song_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Song_ID) REFERENCES Songs(ID) ON DELETE CASCADE
);

CREATE TABLE Playlist (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(30) NOT NULL,
    User_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE SongPlaylist (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Song_ID UNIQUEIDENTIFIER NOT NULL,
    Playlist_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Song_ID) REFERENCES Songs(ID),
    FOREIGN KEY (Playlist_ID) REFERENCES Playlist(ID),
    CONSTRAINT unique_song_playlist UNIQUE (Song_ID, Playlist_ID)
);

CREATE TABLE Roles (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Code NUMBER(1) NOT NULL,
    Name NVARCHAR(20) NOT NULL,
    CONSTRAINT unique_code_role UNIQUE (Code)
);

CREATE TABLE UserRoles (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Role_Code NUMBER(1) NOT NULL,
    User_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (Role_Code) REFERENCES Roles(Code),
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE RolesPermissions (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Permission_Code NVARCHAR(5),
    Role_Code NVARCHAR(5),
    FOREIGN KEY (Permission_Code) REFERENCES Permissions(Code),
    FOREIGN KEY (Role_Code) REFERENCES Roles(Code)
);

CREATE TABLE Permissions (
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    Code NVARCHAR(5)
    Name NVARCHAR(30)
)