CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Password VARCHAR(30) NOT NULL,
    Salt VARCHAR(5) NOT NULL
);

CREATE TABLE Media (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL
);

CREATE TABLE Songs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Media_ID INT NOT NULL,
    FOREIGN KEY (Media_ID) REFERENCES Media(ID) ON DELETE CASCADE
);

CREATE TABLE Playlist (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    User_ID INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE SongPlaylist (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Song_ID INT NOT NULL,
    Playlist_ID INT NOT NULL,
    FOREIGN KEY (Song_ID) REFERENCES Songs(ID),
    FOREIGN KEY (Playlist_ID) REFERENCES Playlist(ID),
    UNIQUE KEY unique_song_playlist (Song_ID, Playlist_ID)